# Generated by Django 3.0.7 on 2020-12-29 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20201205_1611'),
        ('applications', '0022_application_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_auto_20201027_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionErrorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content', models.TextField(max_length=255, verbose_name='Conteúdo da mensagem')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='applications.Application', verbose_name='Aplicação')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='questions.Question', verbose_name='Questão')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Erro em questão',
                'verbose_name_plural': 'Erros em questões',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
